# This file automatically overrides docker-compose.yml in development
# No need to specify with -f flag when using docker-compose up

services:
  frontend:
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev

  ai_service:
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
    command: /app/.venv/bin/python -m uvicorn ai_service.api.main:app --host 0.0.0.0 --port 8000 --reload
