apiVersion: apps/v1
kind: Deployment
metadata:
  name: birth-time-rectifier-ai
  labels:
    app: birth-time-rectifier
    component: ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: birth-time-rectifier
      component: ai
  template:
    metadata:
      labels:
        app: birth-time-rectifier
        component: ai
    spec:
      containers:
        - name: ai-service
          image: ghcr.io/birth-time-rectifier-ai:latest
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: REDIS_URL
              value: "redis://birth-time-rectifier-redis:6379/0"
            - name: CUDA_VISIBLE_DEVICES
              value: "0"
            - name: GPU_MEMORY_FRACTION
              value: "0.7"
          resources:
            requests:
              cpu: "500m"
              memory: "2Gi"
              nvidia.com/gpu: 1
            limits:
              cpu: "2000m"
              memory: "4Gi"
              nvidia.com/gpu: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4
---
apiVersion: v1
kind: Service
metadata:
  name: birth-time-rectifier-ai
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: birth-time-rectifier
    component: ai 