apiVersion: apps/v1
kind: Deployment
metadata:
  name: birth-time-rectifier-frontend
  labels:
    app: birth-time-rectifier
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: birth-time-rectifier
      component: frontend
  template:
    metadata:
      labels:
        app: birth-time-rectifier
        component: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/birth-time-rectifier-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_API_URL
              value: "http://birth-time-rectifier-ai:8000"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: birth-time-rectifier-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: birth-time-rectifier
    component: frontend 