apiVersion: apps/v1
kind: Deployment
metadata:
  name: birth-time-rectifier-redis
  labels:
    app: birth-time-rectifier
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: birth-time-rectifier
      component: redis
  template:
    metadata:
      labels:
        app: birth-time-rectifier
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          command:
            - redis-server
            - --appendonly
            - "yes"
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: birth-time-rectifier-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: birth-time-rectifier
    component: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 